

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddc-server
  labels:
    app: ddc-server
    app.kubernetes.io/part-of: ddc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddc-server
  template:
    metadata:
      labels:
        app: ddc-server
        app.kubernetes.io/part-of: ddc
    spec:
     # initContainers:
     # - name: bootstrap-content
     #   image: busybox:1.28
     #   command: ["/bin/sh", "-c"]
     #   args:
     #     - echo starting ;
     #       mkdir -p /home/node/app/node_modules ;
     #       chown -R node:node /home/node/app ;
     #       cd /home/node/app ;
     #       #su node ;
     #       #npm install ;
     #       #chown node:node . . ;
      containers:
        - name: ddc-server
          image: node:10-alpine
          imagePullPolicy: IfNotPresent
          command: ["node bin/www"]
          ports:
            - containerPort: 3000
              name: ddc
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi
---

apiVersion: v1
kind: Service
metadata:
  name: ddc-service
  labels:
    app: ddc-service
    app.kubernetes.io/part-of: ddc
spec:
  ports:
    - name: ddc-port
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: ddc-server
